services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"  # MQTT broker
    volumes:
      - ./compose/mosquitto/config:/mosquitto/config
      - ./compose/mosquitto/mosquitto/data:/mosquitto/data
      - ./compose/mosquitto/log:/mosquitto/log
    networks:
      - mqtt-net

networks:
  mqtt-net:
    driver: bridge
